### ISSUE TITLE
Dashboard optimization

### ISSUE THREAD

**Issue by garudaonekh** [kizniche/Mycodo#996]
I see the dashboard is getting very heavy due to loading of all the output options, inputs,....

I think we should have two modes, ie display and edit, where in display mode only the display items are seen and loaded.

Do you have any other suggestion?

One more thing, I see that the dashboard depends heavily on the API(which i find it very good) so is it feasible to separate the dashboard into another app(multi tier) so that we can remotely manage main Mycodo system?

**Comment by kizniche** [comment]
I've never experienced what you describe, even on devices with low resources such as my phone. Can you provide a screenshot of the kind of dashboard you're describing and list the specs of the computer rendering it in your web browser?

**Comment by chamroeunbm** [comment]
Your code list all the output/input so I if have 50 input and there're 50 widget, the HTML page will list 50 times of that 50 inputs which increase the HTML size a lot.

**Comment by kizniche** [comment]
It's actually not a lot of HTML. Many JS source files are 10x and even 100x larger than the scenario you describe. You also likely don't have 50 inputs nor 50 widgets on your desktop. I'm asking for you to demonstrate the issue you say you have.

**Comment by chamroeunbm** [comment]
Currently, I have 16 inputs mostly wireless(Mijia, FLowercare). Flowercare alone has 5 channels--thus it will list as 5 inputs. We're having 50+ soon as in a greenhouse, we'll have up to 6 soil moisture + other sensors. There's no problem to open it from my laptop locally. But I try to remote it but that come the problem of dashboard exceed 2.5MB(html, javascript...). I am trying to find a way to optimize it.

**Comment by kizniche** [comment]
I could add a dashboard option "lock dashboard" which would remove the widget option HTML from the page.

**Comment by kizniche** [comment]
I just added the ability to lock dashboards. If you [upgrade to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch), you can try it out before release. If you do, let me know what kind of performance improvement you see and perhaps compare the number of source lines when locked and unlocked.

**Comment by kizniche** [comment]
Just pushed another change that further reduces the size by removing the Add Widget dropdown at the bottom when locked.

**Comment by garudaonekh** [comment]
When locked, most of the input widgets are not displaying any image or data, the graph are not displaying any data maybe javascript issue. The output widget is ok.

**Comment by kizniche** [comment]
That's not happening for me. You're going to have to provide a bit more information: JS errors, browser inspection, etc.

**Comment by garudaonekh** [comment]
<img width="1654" alt="Screen Shot 2021-05-27 at 9 26 20 PM" src="https://user-images.githubusercontent.com/2074857/119844042-49a8c780-bf32-11eb-9149-fa3a8f595186.png">
<img width="1656" alt="Screen Shot 2021-05-27 at 9 26 33 PM" src="https://user-images.githubusercontent.com/2074857/119844064-4dd4e500-bf32-11eb-9923-4416aa826981.png">

There's 1 javascript error, I think this error may be the problem: 

`Uncaught ReferenceError: decimal_places is not defined
    getLastDataGaugeAngular 2a457a9e-3cde-486c-82f9-e173300618aa:931
    `

**Comment by kizniche** [comment]
Thanks. I just committed a fix.

**Comment by garudaonekh** [comment]
The error still happen on existing widget(I tried both widgets that you updated).

The following error occurred when add widget in dashboard.

`Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 652, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 626, in page_dashboard
    unmet_dependencies = utils_dashboard.widget_add(form_base, request.form)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/utils/utils_dashboard.py", line 239, in widget_add
    control.widget_add_refresh(new_widget.unique_id)
  File "/home/pi/Mycodo/mycodo/mycodo_client.py", line 296, in widget_add_refresh
    return self.proxy().widget_add_refresh(unique_id)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/Pyro5/client.py", line 476, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/Pyro5/client.py", line 243, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
AttributeError: 'NoneType' object has no attribute 'widget_add_refresh'`

**Comment by garudaonekh** [comment]
the unlock html file of my dashboard is 1 MB, now it's  270K, so it's nearly 75% decrease in size. That's fantastic

**Comment by kizniche** [comment]
Did you upgrade to master?

**Comment by garudaonekh** [comment]
After I am back from lunch and restart the service(both Mycodo and flask), it works ok now.
